language: python
python:
  - "3.6.4"

install:
  - pip install coverage
  - pip install coveralls
  - pip install nosexcover
  - pip install -r requirements.txt

services:
  - postgresql
env:
  global:
    - export SECRET="hard to guess string"
    - export APP_SETTINGS="development"
    - export DATABASE_URL="postgresql://postgres:clerry@localhost/weconnect"
before_script:
  - psql -c "CREATE DATABASE weconnect;" -U postgres
script:
  - nosetests --with-coverage --cover-package=app/api && coverage report
after_success:
  - coveralls