language: python
python:
  - "3.6.4"

install:
  - pip install coverage
  - pip install coveralls
  - pip install nosexcover
  - pip install -r requirements.txt

script:
  - nosetests --with-xcoverage --cover-package=app.models --cover-tests

after_success:
  - coverage report
  - coveralls