"""empty message

Revision ID: 8bae784b3631
Revises: d911ded98b7f
Create Date: 2018-03-26 00:58:58.358317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bae784b3631'
down_revision = 'd911ded98b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'user_id')
    # ### end Alembic commands ###
