"""empty message

Revision ID: 96229482543c
Revises: b327476c13d3
Create Date: 2018-03-24 20:53:28.150454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96229482543c'
down_revision = 'b327476c13d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_constraint('businesses_user_id_fkey', 'businesses', type_='foreignkey')
    op.create_foreign_key(None, 'businesses', 'users', ['created_by'], ['id'])
    op.drop_column('businesses', 'user_id')
    op.add_column('reviews', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'added_by')
    op.add_column('businesses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.create_foreign_key('businesses_user_id_fkey', 'businesses', 'users', ['user_id'], ['id'])
    op.drop_column('businesses', 'created_by')
    # ### end Alembic commands ###
