"""empty message

Revision ID: ab4e93b04f9f
Revises: 8bae784b3631
Create Date: 2018-03-26 01:16:39.362024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4e93b04f9f'
down_revision = '8bae784b3631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
