"""empty message

Revision ID: b327476c13d3
Revises: 19ca2c7496dd
Create Date: 2018-03-22 16:56:31.550377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b327476c13d3'
down_revision = '19ca2c7496dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
