"""empty message

Revision ID: c6da8ded35e7
Revises: 2a56beeb3b9e
Create Date: 2018-07-06 12:52:48.651132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6da8ded35e7'
down_revision = '2a56beeb3b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('businesses_created_by_fkey', 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'created_by')
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.add_column('businesses', sa.Column('created_by', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.create_foreign_key('businesses_created_by_fkey', 'businesses', 'users', ['created_by'], ['username'])
    # ### end Alembic commands ###
