"""empty message

Revision ID: d04c26307292
Revises: ab4e93b04f9f
Create Date: 2018-03-26 14:41:06.552680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04c26307292'
down_revision = 'ab4e93b04f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_added_by_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'added_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_added_by_fkey', 'reviews', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###
