"""empty message

Revision ID: d911ded98b7f
Revises: 96229482543c
Create Date: 2018-03-26 00:49:45.963223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd911ded98b7f'
down_revision = '96229482543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('businesses_created_by_fkey', 'businesses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('businesses_created_by_fkey', 'businesses', 'users', ['created_by'], ['id'])
    op.alter_column('businesses', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
